server:
  port: 8000
  ssl:
    enabled: true
    # key-store: keystore.p12
    key-store: classpath:keystore.p12 #(로컬뿐 아닌 개발서버에서도 사용하려면)
    key-store-password: Vita500!
    key-store-type: PKCS12
    key-alias: bns-ssl

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8b106.p.ssafy.io:3306/vita?serverTimezone=Asia/Seoul
    username: vita
    password: Vita500!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true   #추가
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: wearable
          uri: http://j8b106.p.ssafy.io:8083/
          predicates:
            - Path=/api/wearable/**
        - id: friend
          uri: http://j8b106.p.ssafy.io:8084/
          predicates:
            - Path=/friend/**
        - id: user
          uri: http://j8b106.p.ssafy.io:8085/
          predicates:
            - Path=/users/**